CERT-Polska/karton

setup.py

This should allow Karton services to use type hints from karton.core

Add PEP 561 typing stub

---

Dockerfile

This is a small quality of life change, for people wanting to add arguments to `karton-system` (for example `--setup-bucket`). In a docker-compose it changes from:
```yml
command: ["karton-system", "--setup-bucket"]
```
to:
```yml
command: ["--setup-bucket"]
```

replace docker run with entrypoint

---

dev/docker-compose.yml
dev/system.Dockerfile

This file is unnecessary (provides no other functionality than main Dockerfile). Moreover, it's just asking to be desynced from main Dockerfile and be a source of frustration and hours of debugging, as it's not used in CI. Could be simplfied more if #84 is merged.

remove dev dockerfile completely

---

.github/workflows/publish.yml
.github/workflows/release.yml

This PR:
- removes push of docker images until they are merged into master
- pushes all commits from master to dockerhub with sha and uses `master` as a pointer to latest image
- pushes all tags to dockerhub with sha, tag name and `latest` as a pointer to latest release
The reasoning for `latest` and `master` dockerhub tags is [here](https://blog.container-solutions.com/docker-latest-confusion).
If this works properly, we can add this to all other related projects.

add better tags on dockerhub

---

.github/workflows/publish.yml
.github/workflows/release.yml

The type accepted by `docker/build-push-action` was surprising.

CI: Fixed publish workflow

---

.github/workflows/publish.yml
.github/workflows/release.yml

Yet another PR that will fix the Docker Hub push (I want to believe).
Based on: https://github.com/docker/build-push-action/issues/100

CI: push-action requires setup-qemu and setup-buildx

---

karton/core/main.py

Cli was created when we didn't have the awesome `KartonBackend`, it allows us to perform the inspection with much less effort and without directly interacting with Redis.
Closes #83

Refactor cli to use KartonBackend

---

karton/core/backend.py
karton/core/karton.py

Some time ago we've added a `version` field for new consumers, this PR exposes them in the bind stored in Redis so we can process these versions in other systems (like dashboard)
Open questions:
* Should it be named `service_version` or `consumer_version`? (or something else)
Closes #69

Expose service version in binds

---

.github/workflows/release.yml

https://github.community/t/how-to-get-just-the-tag-name/16241/21
I hope it doesn't require the actual `release` event instead of `push`

CI: Use 'push' event for release

---

karton/core/base.py
karton/core/logger.py

When using loggers other than the default (`getLogger(self.identity)`), `name` in LogRecord will be wrong and routed as other origin.
Pass the identity explicitly to fix this

Pass service identity as logger name

---

karton/core/base.py
karton/core/logger.py

This change ensures that output of KartonLogHandler doesn't depend on
other formatters setting the "message" field. This would break if the
handler was added to a logger without any other handlers.

Add formatter to KartonLogHandler

---

Dockerfile
karton/core/backend.py
karton/core/main.py

Almost everything has been turned upside down
* use subparser instead of arguments for the root handler
* add a new `configure` option
* setup logging
* add a few utility arguments

Upgrade karton cli

---

karton/core/resource.py

Since `ResourceBase` accepts `Optional[Union[str, bytes]]` I think it makes no sense in limiting ourselves to bytes there

Fix type typo in LocalResource constructor

---

karton/core/backend.py

Expose the metrics via the backend API, so we can code https://github.com/CERT-Polska/karton-dashboard/pull/39 more cleanly

Expose karton metrics via the backend API

---

karton/core/resource.py

Support for retreiving content from resources without an explicit content load:
```python
config_res = Resource(name="config.json", path=config_path)
config = json.loads(config_res.content.decode())
```
This has a nice side-effect of typing `.content` property more strictly (it becomes `bytes` instead of `Optional[bytes]`)

Add a lazy loaded content to the local resource

---

karton/core/resource.py

Use another variable instead of 'name' when looping over files in
directory. 'name' is already used as an argument and will be accidentally
destroyed during iteration.

core/LocalResource: Don't overwrite resource name

---

karton/core/backend.py
karton/core/karton.py

This change set adds the ability for karton instances to signal to downstream
consumers about the beginning and ending of task execution. Signaling is
performed by sending corresponding "status" tasks.
Task signaling is enabled using the following entry in the karton
configuration file:
```
[signaling]
status = 1
```
Task signaling is disabled by default.

implement status signaling

---

karton/core/config.py

Now you can 
```python
from karton.core.Config import Config
config = Config.from_dict({
"minio": {...},
"redis":  {...},
})
```
It's ugly, but it works!

config: Add from_dict method

---

karton/core/resource.py
karton/core/task.py

Fix following warnings from Sphinx:
docstring of karton.core.task.Task:7: WARNING:
Inline interpreted text or phrase reference start-string without end-string.
docstring of karton.core.resource.LocalResource:6: WARNING:
Could not lex literal_block as "python". Highlighting skipped.

doc: Fix syntax errors

---

karton/core/backend.py
karton/core/karton.py
karton/system/system.py

Ok so I will put in my two cents to the routing optimization.
- Currently routing is too heavy because it takes care of non-persistent queue unwinding and setting task statuses
- Task status can be set directly by consumers. It doesn't break anything because exclusive task ownership is gathered at the time of popping task out of the queue 
Let's take a look at current task lifetime:
```
1. [PRODUCER] Declares unrouted task with status DECLARED
Used rresources are referenced and locked from now
2. [PRODUCER] Uploads resources to Minio
3. [PRODUCER] Adds task to unrouted queue
Task identifier passed to the queue, which passes the task ownership to ANY ROUTER
4. [ANY ROUTER] Gathers unrouted task from the queue
The first router that gets the task has the ownership
5. [ONE ROUTER] Performs …
```

System routing revisited - prepare to parallelization

---

karton/core/resource.py

Add the possibility to set suffix to temporary file. Some workarounds requires to set specifix suffix (e.g. some metadata carving applications requires the proper extension), this way it will be convenient to have a possibility to set it.

download_temporary_file - add suffix to temp file

---

karton/core/backend.py

Currently, the outputs are stored for an hour. For most systems, an hour doesn't represent the system.
A day isn't very representative, a week is somewhat representative, and a month is pretty accurate.
The difference in store space between an hour and a day isn't much, so is between a day and a month, But the little diff is still very meaningful. 
context: relations graph

Store outputs for 30 days

---

karton/system/system.py

Change from `ensure_bucket_exsits` to `ensure_bucket_exists`
Couldn't find any other reference to this method.

Fix typo in one of system method

---

karton/core/resource.py

It's a comment that was left after my failure to make a more generic abstraction on resource metadata. Let's just forget about it

resource.py: metadata["sha256"] is not deprecated

---

karton/system/system.py

Issue: https://github.com/CERT-Polska/karton/issues/147
Config example:
```toml
[minio]
secret_key = minioadmin
access_key = minioadmin
address = localhost:9000
bucket = karton
secure = 0
[redis]
host=localhost
port=6379
[mongo]
host=localhost
port=27017
[task_timeouts]
GC_INTERVAL = 60
TASK_STARTED_TIMEOUT =2592000
TASK_CRASHED_TIMEOUT = 2592000
```

Option to set gc parameters in config

---

.github/workflows/test.yml
karton/core/backend.py
karton/core/base.py
karton/core/karton.py

Identity is set via constructor, so it should be passed to KartonBackend and set as `client_name` argument in StrictRedis object.
Closes #169

Fix: Redis client name is lost after reconnection

---

docs/unit_tests.rst
karton/core/test.py
tests/math_test_case/math_karton.py
tests/math_test_case/test_math_karton.py
tests/reverser_test_case/reverser_karton.py
tests/reverser_test_case/test_reverser_karton.py

Few important fixes:
- Task forking and resource upload mock was completely missing, so tested Karton was receiving task with useless LocalResource
- Found errors in code snippets in documentation
Test cases from documentation were added to actual tests.
Closes #149

Fix test utils and provide test cases for karton.core.test

---

karton/core/backend.py

By default it seems to come without any timeout.
When I pretend to be a silent server (e.g. proxy with incorrect handling of dropped connection on the other side), it waits forever for an answer. When socket_timeout is set, after 30 seconds it raises `redis.exceptions.TimeoutError: Timeout reading from socket`.
```
$ nc -l 9999
*3
$6
CLIENT
$7
SETNAME
$18
karton.wait-for-it
```
Closes #136

Redis: Set default socket_timeout and support db/username keys

---

karton/core/base.py
karton/core/karton.py
karton/core/main.py
karton/core/utils.py
karton/system/system.py

Signal handlers should not be set inside the constructor of Karton class, because in case of incorrect invocation:
```
KartonClass().main()
```
KartonClass instance is set twice and `GracefulKiller` doesn't correctly fallback to default handler. I replaced it with context manager and raising own exception (`HardShutdownInterrupt`) in case of second try.
~~In previous implementation, second try handler was spawned only when second SIGINT arrived. Should we do the same for SIGTERM?~~ After short research I think hard shutdown should be implemented only for SIGINT.

Correctly handle SIGINT/SIGTERM for graceful exit

---

karton/core/backend.py
karton/core/config.py
karton/core/main.py
karton/core/resource.py
karton/core/test.py
karton/system/system.py
requirements.txt
setup.cfg
tests/test_core.py

MinIO is S3 compatible so it may make sense to use just S3 compatible lib instead of minio-py - this also allows to use other S3-compatibile storage such as amazon or ceph

S3 support

---

karton/core/backend.py
karton/core/resource.py

- `fd` is expected as one of LocalResource content sources (closes #29)
- `LocalResource.from_directory` is using TemporaryFile instead of NamedTemporaryFile and access by path
- Typing: mypy says that `IO[bytes]` is incompatible with `BinaryIO` and it looks like the first form is preferred. 
Quite unexpected by just reading the documentation (https://docs.python.org/3/library/typing.html#typing.BinaryIO) but there are some extra methods added (https://github.com/python/typeshed/blob/master/stdlib/typing.pyi#L700).

Fix handling on LocalResource with file descriptor as a source

---

docs/task_headers_payloads.rst
karton/core/karton.py
karton/core/task.py
karton/core/test.py
karton/core/utils.py
karton/system/system.py
tests/nested_resources_test_case/multi_reverser_karton.py
tests/nested_resources_test_case/test_multi_reverser_karton.py

Support for nested resources

---

karton/core/backend.py

- Introducing pagination in `list_objects` method in order to return all the objects contained within a given bucket;
- Chunking the list of objects to be removed with `remove_objects` method to avoid raising exceptions in case of list bigger than 1000 elements.

Fix list_objects and remove_objects methods

---

karton/core/backend.py
karton/core/base.py
karton/core/exceptions.py
karton/core/karton.py
karton/system/system.py

It would be nice to have version information also for looping producers (feeders), log consumers and other services that are part of Karton pipeline.
In this PR I'm adding these informations as a part of client name in the following URI like format:
```
karton.producer?karton_version=5.1.0&service_version=1.0.0
```
Client name is currently used only by consumers to count the replicas and track for abandoned non-persistent queues, so it's not a breaking change if we include extra information for non-consumers. Information is included to client name only if `KartonBase.with_service_info` class attribute is set to True (False by default).
Attached version information can be then displayed in Karton Dashboard (see also https://github.com/CERT-Polska/karton-dashboard/pull/72)

Extended service information for non-consumer services

---

docs/getting_started.rst

Before this change it was rendering to `https://karton-core.readthedocs.io/en/latest/github.com/CERT-Polska/karton-playground/` :face_with_head_bandage:

Docs: Update broken link in 'Getting Started'

---

karton/core/config.py

It will allow us to configure sections like `archive-unpacker` and `mwdb-reporter` using the environmental variables.

Allow dashes in config section names configured by env

---

docs/task_headers_payloads.rst
karton/core/karton.py
karton/core/task.py

Reasons to implement that:
- They make a good place for "properties" idea from https://github.com/CERT-Polska/karton/issues/167. 
- It's also follow up from https://github.com/CERT-Polska/mwdb-core/pull/801 as we don't propagate `share_3rd_party` header within karton-archive-extractor. 
- Another painful header is `quality` that needs to be passed manually from task to task: https://github.com/CERT-Polska/karton-classifier/blob/master/karton/classifier/classifier.py#L102
Few design details:
- They follow the same semantics as persistent payloads, but both persistent and non-persistent headers are available from the same dict to keep it easier for users. Both internal and service code tends to directly modify `self.headers` collection so it was important also for compatibility.
- Copy of …

Feature: persistent headers

---

docs/service_examples.rst

Recently needed functionality similar to the Producer example code, copy pasted it and found it is outdated and broken.
* Add missing imports
* Fix `name` -> `filename` for the code to run
* Use `add_payload` as `add_resource` as been deprecated

Update producer example in docs

---

.gitignore
docs/advanced_concepts.rst
docs/service_configuration.rst
karton/core/base.py
karton/core/karton.py

The karton debug mode helps with developing karton services while connected to the production karton network. It does that by:
* appending a random suffix to the karton service identity to avoid disrupting production services
* permanently setting the `persistent` attribute to False - the bind will disappear after the service quits
* not sending the (error) logs to karton listeners - this will help you to avoid spamming logging services in your deployment
The debug mode works as any other karton configuartion and can be set by:
* setting the env value `KARTON_KARTON_DEBUG=1`
* setting `debug=1` in the `karton` section in `karton.ini`
* passing `--debug` to karton services via cli

Introduce karton debug

---

karton/core/task.py
tests/test_task_filters.py

Issue reported here: https://github.com/CERT-Polska/karton/issues/222
I have just refactored the code in order to keep the matching logic the same and at the same time to take into account the use case that is causing the wrong matching when filters have more negated fields that matches the headers values.
I have also updated the unittest related to the task filters with negation.
```
In [1]: from karton.core import Task
In [2]: Task({
...:     "type": "sample",
...:     "kind": "runnable",
...:     "platform": "win32",
...:     "extension": "msix"
...: }).matches_filters([
...:         {"type": "sample", "kind": "runnable", "platform": "win*", "extension": "!msi*"},
...:         {"type": "sample", "kind": "runnable", "platform": "win*", "extension": "!lnk"},
...:         {"type": …
```

Fix issue #222 with matches_filters method

---

pyproject.toml

Redis-py laziness in defining types results in the following errors:
```
karton/core/backend.py:276: error: Argument 2 to "unserialize_bind" of "KartonBackend" has incompatible type "Union[Awaitable[Optional[str]], str, None]"; expected "str"
karton/core/backend.py:287: error: Item "Awaitable[Dict[Any, Any]]" of "Union[Awaitable[Dict[Any, Any]], Dict[Any, Any]]" has no attribute "items"
karton/core/backend.py:287: note: Maybe you forgot to use "await"?
karton/core/backend.py:312: error: Argument 2 to "hdel" of "HashCommands" has incompatible type "str"; expected "List[Any]"
karton/core/backend.py:334: error: Item "Awaitable[Any]" of "Union[Awaitable[Any], Any]" has no attribute "__iter__" (not iterable)
karton/core/backend.py:355: error: Item "Awaitable[Any]" of "Union[Awaitable[Any], …
```

CI: Fix lint-python after Redis v5.0.0 release

---

docs/service_configuration.rst
karton/core/backend.py
pyproject.toml

This PR adds the ability to support IAM authentication using a `iam_auth` boolean option in the `[s3]` section of karton.ini, much like in MWDB.
Testing was done on `karton-core v5.2` and `mwdb-core v2.8.2`, by omitting the `access_key` and `secret_key` from karton.ini and making sure everything is functional:  
* File upload to mwdb
* File reanalysis
* Making new kartons
This PR is marked as draft because the [configuration wizard](https://github.com/CERT-Polska/karton/blob/master/karton/core/main.py#L35C13-L35C13) of Karton seems like an ancient piece of code and I'm not sure if I should add this option to it or not

S3 client: add IAM configuration

---

karton/core/backend.py

Closes #236 
When `backend.register_tasks` - https://github.com/CERT-Polska/karton/blob/2d10bd432928354a2030a0ee8aa976b64f4acb63/karton/core/backend.py#L542 is called with an empty list of tasks to create it results in a crash when calling `mset`:
`redis.exceptions.ResponseError: wrong number of arguments for 'mset' command`
Reproduction:
Downgrade to <4.4.0, create a new task and create a new "NOP" operational task by setting the task status to its current value:
```python
producer = Producer(identity="test-producer")
headers = {
"kind": "raw",
"type": "sample"
}
t = Task(headers=headers, payload={
"sample": "sample",
})
producer.send_task(t)
producer.backend.set_task_status(t, TaskState.DECLARED)
```

Fix issues with `register_tasks` and empty tasks list

---

karton/core/backend.py

This PR solves the issue described in #233. Botocore's `*Provider` classes such as `ContainerProvider` return a `RefreshableCredentials` object when calling their `load` method. This object knows when and how to refresh the session token, so there's no need to implement custom code to do that. In current code, this object is thrown away so it gets no chance to auto-refresh the token.
Instead, use a lower level session object and if possible, attach this `RefreshableCredentials` object to it, and create the s3 client from it. 
Tested on MWDB v2.10.2 with a karton that uses v5.3.0 of karton-core with the diff in this PR patched into it and seems to still work even a couple of hours after the karton is up (whereas the current code fails). Kept as draft until I'm sure it solves the issue …

Fix IAM token expiration

---

karton/core/exceptions.py

Task timeout function sets alarm that triggers SIGALRM, which is then handled by throwing TaskTimeoutError. This mechanism should crash task that is running too long e.g. because of infinite loop or other conditon that caused the consumer to be hanged.
Unfortunately, TaskTimeoutError derives from Exception base class which means that it will be cached by any `try..except` clause that catches all Exceptions, which is pretty common pattern in Python, making timeout ineffective. This kind of situation happens in karton-config-extractor and malduck: https://github.com/CERT-Polska/malduck/blob/master/malduck/extractor/extractor.py#L447
This PR changes base class of TaskTimeoutError from Exception to BaseException (like GracefulShutdown).
> BaseException is the common base class of all …

TaskTimeoutError should be BaseException instead of Exception

---

karton/system/system.py

Those two scenarios shouldn't happen in a "healthy" environment. By using error instead of warning they will be easier to spot and resolve.

Use error instead of warning when tasks are killed due to inactivity

---

karton/core/karton.py

#241 changed the base type of `TaskTimeoutError` from `Exception` to `BaseException`. This caused the exception handlers on https://github.com/CERT-Polska/karton/blob/master/karton/core/karton.py#L182 and https://github.com/CERT-Polska/karton/blob/master/karton/core/karton.py#L189 to not catch the timeout and crash the karton service alltogether.
Minimal test case:
```python
from karton.core import Consumer, Task
from time import sleep
class TimeoutTest(Consumer):
identity = "karton.timeout-test"
filters = [{}]
def __init__(self, *args, **kwargs) -> None:
super().__init__(*args, **kwargs)
self.task_timeout = 5
def process(self, task: Task) -> None:
print(task.headers)
sleep(6)
if __name__ == "__main__":
TimeoutTest.main()
```
pre-patch:
```
[2024-03-25 13:44:02,642][INFO] Received new …
```

Fix TaskTimeoutException regression

---

karton/core/backend.py
karton/core/task.py

- It's not necessary to exclude `backend` (value is always valid, in case of `parse_resources=False` it's just unused)
- Don't fallback from `parse_resources=False` to `parse_resource=True` equivalent when orjson fails to deserialize JSON
Edit: after discussion, we removed fallback to json at all

Fix: simplify task deserialization code, don't deserialize resources when orjson fails

---

docs/advanced_concepts.rst
docs/task_headers_payloads.rst
karton/core/karton.py
karton/core/query.py
karton/core/task.py
karton/system/system.py
tests/test_core.py
tests/test_task_filters.py

This adopts code from https://github.com/kapouille/mongoquery to implement a mongodb-like syntax for task filtering in karton.
As mentioned in the code, there are some pitfalls since the old negative matching works in three-state logic and can't be translated to the new query syntax literally. For a short example:
```json
[
{"platform": "!win32"},
{"platform": "!linux"}
]
```
will match all non-linux non-windows samples, as was probably intended, but:
```json
[
{"platform": {"$not": "win32"}},
{"platform": {"$not": "linux"}}
]
```
is wrong - this means literally `task.headers["platform"] != "win32" or task.headers["platform"] != "linux"` and hence will match every task.
To get equivalent behaviour with mongo syntax, you should use:
```json
[{
"platform": {
"$not": { "$or": ["win32", …
```

Implement mongodb query syntax for task filters

---

karton/core/query.py
tests/test_task_filters.py

v5.5.0 introduced regression for negated boolean old-style filters. Because negation was done by adding "!", filter matching function was doing an implicit header value conversion to string.
This behavior was unintentionally changed by v5.5.0 as new-style (Mongo-style) filters don't perform any type coercions. 
One of the affected components by this regression is Drakvuf Sandbox that uses `{"execute": "!False"}` to filter out all samples that should not be executed. These samples are marked with `{"execute": False}` header, so conversion to string in this case is expected.

Fix regression: missing string coercion for old-style negated filters

---

.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test.yml

CPython 3.7 and 3.8 is no longer served by setup-python action

CI: Upgrade setup-python, test on CPython 3.9-3.12 instead of 3.7-3.9

---

karton/system/system.py

Hello!
This PR introduces alternative behavior for STARTED tasks on their timeout.
For now karton deletes such tasks, but in certain scenarios it's preferable to crash them.
Also this PR shows effective config applied on karton dispatcher to ease testing with mixed parameter sources (command-line args, karton.ini, default values).

Optional feature: crash started task on timeout instead of deleting

---

karton/core/karton.py

Hello!
While examining your `karton-core` code, I found karton.task_timeout config parameter (it also described in docs).
Sometimes it could hard to use united timeout for services (for example, you expect 'karton-yara' to work at most 30 sec, and 'karton-drakvuf' at most 10 mins), so it's preferable to allow custom settings for each Consumer.
This PR introduces Consumer.task_timeout that this behaviour:
- `None` - use global value described in config file.
- `0` - disable global-set task timeout.
- positive integer - kill task on timeout.

Allow to override task timeout for consumer class

---

karton/core/backend.py
karton/core/base.py
karton/core/logger.py
karton/system/system.py

- Added a flag to enable/disable log publishing to Redis
- Added a flag to enable/disable the task tracking on Redis
- Added settings to specify Redis TTL for the task tracking info
It would be nice to provide the settings to give the freedom to the end user to decide whether to enable or disable logs publishing to Redis and the task tracking feature.

Add optional log publishing + task tracking settings

---

karton/core/asyncio/base.py
karton/core/asyncio/karton.py
karton/core/base.py
karton/core/config.py
karton/core/logger.py

- Critical fix: releasing concurrency_semaphore after `consume_routed_task` returned None (due to timeout). Right now, consumer is hanging after few seconds.
- Set default concurrency_limit to 1 (much safer default)
- Added task_id to Karton log entries for asyncio Karton services to distinguish records coming from concurrent tasks

Various asyncio fixes and improvements

---

karton/core/asyncio/karton.py
karton/core/karton.py

Hello! This PR introduces small QoL change that will be helpful in troubleshooting of bind change reasons.

Better verbosity of filter change

---

requirements.txt

After bump in 5.8.0, once again we hit the problem described in https://github.com/CERT-Polska/karton/pull/270. The fix proposed in https://github.com/CERT-Polska/karton/pull/289 doesn't help

Downgrade boto3 to <1.36.0 and aioboto3 to 13.3.0

---

docs/service_configuration.rst
karton/core/asyncio/backend.py
karton/core/backend.py

Additional details:
- Configuration dict is built in KartonBackendBase
- Added `del redis_args["username"], because `del redis_args["password"]` just returns error about wrong number of AUTH arguments. Personally I'm against such fallbacks but let's just fix it this time.
closes https://github.com/CERT-Polska/karton/issues/280

Add url and ssl options to Redis configuration

---

karton/core/asyncio/backend/__init__.py
karton/core/asyncio/backend/base.py
karton/core/asyncio/backend/direct.py
karton/core/asyncio/base.py
karton/core/asyncio/karton.py
karton/core/asyncio/logger.py
karton/core/asyncio/resource.py
karton/core/backend/__init__.py
karton/core/backend/base.py
karton/core/backend/direct.py
karton/core/base.py
karton/core/karton.py
karton/core/logger.py
karton/core/resource.py
karton/core/task.py
karton/system/system.py
pyproject.toml

This is a first PR introducing changes required for implementing an alternative Karton backend called "Karton Gateway". It's going to use websockets and presigned S3 URLs instead of relying on Redis and S3 operations directly.
- Karton services (Consumers, Producers, integrations) are going to use `get_backend` method to create appropriate backend based on Karton configuration (`karton.ini`).
- Backend interface for services is well defined by [Protocol](https://typing.python.org/en/latest/spec/protocol.html) and defines set of methods that must be implemented in all backends used by Karton services.
- Internal services still use "direct" backend to perform operations directly on Redis/S3. Karton System uses the sync direct backend and future Karton Gateway server is going to use the …

[v6] Introduce backend factory and KartonBackendProtocol interface

---

karton/core/asyncio/backend/__init__.py
karton/core/asyncio/backend/direct.py
karton/core/asyncio/base.py
karton/core/backend/__init__.py
karton/core/backend/base.py
karton/core/backend/direct.py
karton/core/base.py
karton/core/karton.py
karton/system/system.py

KartonServiceInfo was introduced in v5.1.0 (https://github.com/CERT-Polska/karton/pull/206) to provide extended version information about other Karton services than consumers. It was opt-in in most cases and `with_service_info = True` flag was required to provide such information. 
Karton Gateway works in a bit different model and extended information contained in KartonServiceInfo is part of regular client identification:
```
class HelloRequestMessage(BaseModel):
identity: str
service_version: str | None
library_version: str
secondary_connection: bool
credentials: AuthCredentials | None = None
```
It enables us to use `karton_version` in future for backwards compatibility.
Notes:
- `get_backend` and Backend constructors still accept the identity argument, similarly to Producer/Consumer …

Refactor: Make KartonServiceInfo the default method for service identification
